CREATE TABLE IF NOT EXISTS public.airport
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    airport_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    airport_full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    country character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT airport_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;
DELETE FROM airport *;
INSERT INTO airport(id, airport_code, airport_full_name, city_name, country) VALUES (1, 'TLL', 'Tallinna Lennujaam', 'Tallinn', 'Estonia');
INSERT INTO airport(airport_code, airport_full_name, city_name, country) VALUES ('URE', 'Kuressaare Airport', 'Kuressaare', 'Estonia');